name: CI/CD Pipeline

on:
  push:
    paths:
      - api/src/**
  workflow_dispatch:
    inputs:
      version:
        description: "Docker image tag (used if no git tag is present)"
        required: false
        default: "latest"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      TAG_NAME: ${{ github.event.inputs.version || 'latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t danblanco/s3-api:${{ env.TAG_NAME }} api/src

      - name: Push Docker image
        run: docker push danblanco/s3-api:${{ env.TAG_NAME }}
